### ISSUE TITLE
Look pic below,type this command "grunt deploy" and press Enter. Print Error on console,why???

### ISSUE THREAD

**Issue by pei-han** [jquery/api.jquerymobile.com#376]
![image](https://cloud.githubusercontent.com/assets/1300292/8324118/397991b8-1a7f-11e5-88a6-b69814aa08d7.png)

**Comment by jaspermdegroot** [comment]
@pei-han 

Everything is explained here: http://contribute.jquery.org/web-sites/#local-development
Maybe you didn't setup ```jquery-wp-content``` properly and/or didn't run ```npm install```.
On that page it's also described how you can get help (http://contribute.jquery.org/web-sites/#getting-help).
Please don't open new tickets here for support questions because this issue tracker is only meant for reporting bugs. Thanks.
