### ISSUE TITLE
libxml2 and libxslt warning (It doesn't generate all contents)

### ISSUE THREAD

**Issue by marti1125** [jquery/api.jquerymobile.com#390]
I added in Mac OS: libxml2 and libxslt
I used this instructions http://ripary.com/libxml2_leopoard.html

$ xmllint --version
xmllint: using libxml version 20902

$ xsltproc --version
Using libxml 20902, libxslt 10128 and libexslt 817
xsltproc was compiled against libxml 20902, libxslt 10128 and libexslt 817
libxslt 10128 was compiled against libxml 20902
libexslt 817 was compiled against libxml 20902

when I try to run grunt deploy I get this
<img width="603" alt="captura de pantalla 2016-03-25 a las 23 33 17" src="https://cloud.githubusercontent.com/assets/223240/14231295/57f6f402-f943-11e5-93ce-3234dc346369.png">

but I had to use grunt deploy --force
<img width="248" alt="captura de pantalla 2016-04-03 a las 00 31 06" src="https://cloud.githubusercontent.com/assets/223240/14231297/6b8a6076-f943-11e5-8cce-79c075b85fb9.png">

the result is:
<img width="888" alt="captura de pantalla 2016-04-03 a las 02 26 37" src="https://cloud.githubusercontent.com/assets/223240/14231300/86349da6-f943-11e5-9537-d7d446c742cb.png">

**Comment by agcolom** [comment]
You need to update you jquery-wp-content.
I'll be out for a bit now, let me know if that doesn't work, and I'll have a look when I get back



On 3 Apr 2016, at 09:27, Willy Aguirre <notifications@github.com<mailto:notifications@github.com>> wrote:


I added in Mac OS: libxml2 and libxslt
I used this instructions http://ripary.com/libxml2_leopoard.html

$ xmllint --version
xmllint: using libxml version 20902

$ xsltproc --version
Using libxml 20902, libxslt 10128 and libexslt 817
xsltproc was compiled against libxml 20902, libxslt 10128 and libexslt 817
libxslt 10128 was compiled against libxml 20902
libexslt 817 was compiled against libxml 20902

when I try to run grunt deploy I get this
[captura de pantalla 2016-03-25 a las 23 33 17]<https://cloud.githubusercontent.com/assets/223240/14231295/57f6f402-f943-11e5-93ce-3234dc346369.png>

but I had to use grunt deploy --force
[captura de pantalla 2016-04-03 a las 00 31 06]<https://cloud.githubusercontent.com/assets/223240/14231297/6b8a6076-f943-11e5-8cce-79c075b85fb9.png>

the result is:
[captura de pantalla 2016-04-03 a las 02 26 37]<https://cloud.githubusercontent.com/assets/223240/14231300/86349da6-f943-11e5-9537-d7d446c742cb.png>

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/jquery/api.jquerymobile.com/issues/390>

The University of Westminster is a charity and a company limited by guarantee. Registration number: 977818 England. Registered Office: 309 Regent Street, London W1B 2UW.

This message and its attachments are private and confidential. If you have received this message in error, please notify the sender and remove it and its attachments from your system.

**Comment by marti1125** [comment]
Hi @agcolom 
<img width="386" alt="captura de pantalla 2016-04-03 a las 02 41 56" src="https://cloud.githubusercontent.com/assets/223240/14231348/b4b74136-f945-11e5-8456-10333e0ea51e.png">
I had the last version =D

I deleted the vm from virtualbox and run again vagrant up

**Comment by marti1125** [comment]
this problem is about parsing xml to html =/ could check it please?

**Comment by marti1125** [comment]
@agcolom could you close this issue please :+1:
